version: '3'
services:
 web:
  image: 'travis_rest:1'
  environment:
   - DB_SERVER=postgresDb
   - ENV_PASSWORD=password
  ports:
   - 8080:8080
 postgresDb:
  image: travis_postgres:latest
  environment:
   - POSTGRES_PASSWORD=password
  volumes:
   - pgdata:/var/lib/postgresql/data
  ports:
   - 5432:5432
volumes:
 pgdata:
